# Codecov configuration to make it a bit less noisy
coverage:
  ignore:
    - qcsubmit/test/.*
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  after_n_builds: 6
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null