site_name: QCSubmit
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      guess_lang: false
repo_name: 'openforcefield/qcsubmit'
repo_url: 'https://github.com/openforcefield/qcsubmit'
plugins:
  - mkdocstrings
  - mkdocs-jupyter
nav:
  - Home: index.md
  - Notebooks:
    - Creating Workflows: creating_workflows.ipynb
    - Collecting Results: Collecting_results.ipynb
  - Reference:
      - Factories: factories.md
      - Datasets: datasets.md
      - Exceptions: exceptions.md
      - Procedures: procedures.md
      - Workflow Components:
          - Base Component: base_component.md
          - Filters: filters.md
          - Conformer Generation: conformer_generation.md
          - State Enumeration: state_enumeration.md

