name: fragmenter
channels:
  - conda-forge

dependencies:

  # Base depends
  - python
  - pip
  - setuptools

  # Sphinx specific
  - nbsphinx
  - nbsphinx-link
  - sphinxcontrib-bibtex
  - pandoc
  - ipython

    # Standard dependencies
  - openff-toolkit-base
#  - rdkit                MOCKED
  - pydantic
  - pyyaml
  - qcportal
  - torsiondrive
  - basis_set_exchange
  - typing-extensions
  - cachetools

  - pip:
      - autodoc_pydantic
      - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
